version: '3.5'
services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile-dev
    volumes:
      - './api:/usr/src/app'
    ports:
      - 5001:5000
    environment:
      - FLASK_APP=project/__init__.py
      - FLASK_ENV=development