version: '3.5'
services:
  api:
    build:
      context: ./services/api
      dockerfile: Dockerfile-dev
    ports:
      - 5000:5000
    environment:
      - FLASK_ENV=development
      - APP_SETTINGS=project.config.DevelopmentConfig