# base image
FROM python:3.6.5-alpine

# Install dependencies
RUN apk update && \
    apk add --virtual build-deps gcc python-dev

# Working directory
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

# Add requirements
COPY ./requirements.txt /usr/src/app/requirements.txt
RUN pip install -r requirements.txt

# Add application
COPY . /usr/src/app

# Run server
CMD gunicorn -b 0.0.0.0:5000 manage:app